import RightSidebar from "@/components/adminComponents/RightSidebar";
import Sidebar from "@/components/adminComponents/Sidebar";
import prismadb from "@/lib/db";
import { ToastProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "../../globals.css";
import { getJustSession } from "@/helpers/get-user-session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getJustSession()
  const dANISMnuser = await prismadb.user.findMany({
    where: {
      role: "DANISMAN",
    },
  });
    const user = await prismadb.user.findUnique({
      where: {
        id: session?.id!,
      },
    });
  const ilann = await prismadb.ilan.findMany({});
  const ilanTipi = await prismadb.ilanTipi.findMany({});

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative w-full h-full flex flex-row max-xl:flex-col max-xl:p-0  justify-between  items-start  bg-[#14213f] min-h-screen">
          <ToastProvider />
          <SessionProvider>
            {session && <Sidebar user={user} />}
            <div className="w-full h-full flex flex-col px-[15px]  gap-[20px] max-xl:p-0 max-xl:gap-0 max-xl:w-full ">

            {session && (
              <RightSidebar
                session={session}
                user={user}
                dANISMnuser={dANISMnuser}
                ilann={ilann}
                ilanTipi={ilanTipi}
              />
            )}
            <div className="py-[15px]">

            {children}
            </div>
            </div>

          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
